"use server";

import { createClient } from "@/lib/supabase/server";
import { createAdminClient } from "@/lib/supabase/admin";
import { revalidatePath } from "next/cache";
import {
  inviteMemberSchema,
  type InviteMemberState,
  type AcceptInvitationState,
  acceptInvitationSchema,
} from "./team-schema";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

type ClinicUserRow = { clinic_id: string; role: string };

type InvitationRow = {
  id: string;
  clinic_id: string;
  email: string;
};

// ---------------------------------------------------------------------------
// inviteMember — admin-only, creates invitation + sends email
// ---------------------------------------------------------------------------

export async function inviteMember(
  _prevState: InviteMemberState,
  formData: FormData,
): Promise<InviteMemberState> {
  const supabase = await createClient();

  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) return { error: "No autenticado" };

  // Admin guard
  const { data: clinicUser } = await supabase
    .from("clinic_users")
    .select("clinic_id, role")
    .eq("user_id", user.id)
    .maybeSingle();

  const cu = clinicUser as ClinicUserRow | null;
  if (!cu) return { error: "Sin clínica asignada" };
  if (cu.role !== "admin")
    return { error: "Solo el administrador puede invitar miembros" };

  // Parse
  const parsed = inviteMemberSchema.safeParse({
    email: formData.get("email"),
    role: formData.get("role"),
    display_name: formData.get("display_name"),
  });

  if (!parsed.success) {
    return { error: parsed.error.issues[0]?.message ?? "Datos inválidos" };
  }

  const { email, role, display_name } = parsed.data;

  // Check existing member
  const { data: existingMember } = await supabase
    .from("clinic_users")
    .select("id")
    .eq("clinic_id", cu.clinic_id)
    .eq("email", email)
    .maybeSingle();

  if (existingMember) {
    return { error: "Este email ya es miembro de la clínica" };
  }

  // Check existing pending invitation
  const { data: existingInvitation } = await supabase
    .from("clinic_invitations")
    .select("id, token")
    .eq("clinic_id", cu.clinic_id)
    .eq("email", email)
    .eq("status", "pending")
    .maybeSingle();

  if (existingInvitation) {
    return { error: "Ya hay una invitación pendiente para este email" };
  }

  // Insert invitation (token generated by DB DEFAULT)
  const { data: inserted, error: insertError } = await supabase
    .from("clinic_invitations")
    .insert({
      clinic_id: cu.clinic_id,
      email,
      role,
      display_name: display_name || null,
      invited_by: user.id,
    } as any)
    .select()
    .maybeSingle();

  if (insertError || !inserted) {
    console.error("[inviteMember] insert error:", insertError);
    return {
      error: insertError
        ? "Error al crear la invitación. Intenta de nuevo."
        : "No se pudo crear la invitación.",
    };
  }

  const invitation = inserted as InvitationRow;

  // Send email via Supabase Admin API
  try {
    const supabaseAdmin = createAdminClient();
    const baseUrl =
      process.env.NEXT_PUBLIC_APP_URL ??
      process.env.NEXT_PUBLIC_VERCEL_URL ??
      "https://recepia-panel.vercel.app";

    // Check if the invited_by is in the invitation row via a separate query
    // because the `invited_by` column may not be in the return type
    const { data: fullInvitation } = (await supabase
      .from("clinic_invitations")
      .select("token")
      .eq("id", invitation.id)
      .maybeSingle()) as { data: { token: string } | null };

    const token = fullInvitation?.token;
    if (!token) {
      console.error("[inviteMember] Could not retrieve token for invitation", invitation.id);
      return { error: "Invitación creada pero no se pudo enviar el email. Contacta con soporte." };
    }

    const redirectTo = `${baseUrl}/auth/accept-invitation?token=${token}`;

    const { error: inviteError } =
      await supabaseAdmin.auth.admin.inviteUserByEmail(email, {
        redirectTo,
      });

    if (inviteError) {
      console.error("[inviteMember] email error:", inviteError);
      // The invitation exists but email failed — not a total failure
      // but we should inform the admin
      return {
        success: true,
        invitation_id: invitation.id,
        error: `Invitación creada pero email no enviado: ${inviteError.message}. Pide al usuario que visite ${redirectTo} directamente.`,
      };
    }
  } catch (err) {
    console.error("[inviteMember] unexpected email error:", err);
    return {
      success: true,
      invitation_id: invitation.id,
      error:
        "Invitación creada pero hubo un error al enviar el email. Intenta reenviar.",
    };
  }

  revalidatePath("/settings/team");
  return { success: true, invitation_id: invitation.id };
}

// ---------------------------------------------------------------------------
// resendInvitation — admin-only, re-sends invitation email
// ---------------------------------------------------------------------------

export async function resendInvitation(
  invitationId: string,
): Promise<InviteMemberState> {
  const supabase = await createClient();

  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) return { error: "No autenticado" };

  const { data: clinicUser } = await supabase
    .from("clinic_users")
    .select("clinic_id, role")
    .eq("user_id", user.id)
    .maybeSingle();

  const cu = clinicUser as ClinicUserRow | null;
  if (!cu) return { error: "Sin clínica asignada" };
  if (cu.role !== "admin") return { error: "No tienes permisos" };

  const { data: invitation } = (await supabase
    .from("clinic_invitations")
    .select("id, email, token, status")
    .eq("id", invitationId)
    .eq("clinic_id", cu.clinic_id)
    .maybeSingle()) as { data: { id: string; email: string; token: string; status: string } | null };

  if (!invitation) return { error: "Invitación no encontrada" };
  if (invitation.status !== "pending")
    return { error: "Esta invitación ya no está pendiente" };

  try {
    const supabaseAdmin = createAdminClient();
    const baseUrl =
      process.env.NEXT_PUBLIC_APP_URL ??
      process.env.NEXT_PUBLIC_VERCEL_URL ??
      "https://recepia-panel.vercel.app";

    const redirectTo = `${baseUrl}/auth/accept-invitation?token=${invitation.token}`;

    const { error: inviteError } =
      await supabaseAdmin.auth.admin.inviteUserByEmail(invitation.email, {
        redirectTo,
      });

    if (inviteError) {
      console.error("[resendInvitation] email error:", inviteError);
      return { error: `Error al reenviar email: ${inviteError.message}` };
    }
  } catch (err) {
    console.error("[resendInvitation] unexpected error:", err);
    return { error: "Error al reenviar. Intenta de nuevo." };
  }

  return { success: true };
}

// ---------------------------------------------------------------------------
// revokeInvitation — admin-only, marks invitation as revoked
// ---------------------------------------------------------------------------

export async function revokeInvitation(
  invitationId: string,
): Promise<InviteMemberState> {
  const supabase = await createClient();

  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) return { error: "No autenticado" };

  const { data: clinicUser } = await supabase
    .from("clinic_users")
    .select("clinic_id, role")
    .eq("user_id", user.id)
    .maybeSingle();

  const cu = clinicUser as ClinicUserRow | null;
  if (!cu) return { error: "Sin clínica asignada" };
  if (cu.role !== "admin") return { error: "No tienes permisos" };

  const query = supabase.from("clinic_invitations") as any;
  const { data: updated, error } = await query
    .update({ status: "revoked" })
    .eq("id", invitationId)
    .eq("clinic_id", cu.clinic_id)
    .eq("status", "pending")
    .select()
    .maybeSingle();

  if (error) {
    console.error("[revokeInvitation]", error);
    return { error: "Error al cancelar. Intenta de nuevo." };
  }

  if (!updated) {
    return { error: "No se pudo cancelar la invitación." };
  }

  revalidatePath("/settings/team");
  return { success: true };
}

// ---------------------------------------------------------------------------
// acceptInvitation — public, called from /auth/accept-invitation
// ---------------------------------------------------------------------------

export async function acceptInvitation(
  _prevState: AcceptInvitationState,
  formData: FormData,
): Promise<AcceptInvitationState> {
  const supabaseAdmin = createAdminClient();

  const parsed = acceptInvitationSchema.safeParse({
    token: formData.get("token"),
    display_name: formData.get("display_name"),
  });

  if (!parsed.success) {
    return { error: parsed.error.issues[0]?.message ?? "Datos inválidos" };
  }

  const { token, display_name } = parsed.data;

  // Find invitation by token (via admin client to bypass RLS)
  const { data: invitation } = (await supabaseAdmin
    .from("clinic_invitations")
    .select("id, clinic_id, email, role, status, expires_at")
    .eq("token", token)
    .eq("status", "pending")
    .maybeSingle()) as {
    data: {
      id: string;
      clinic_id: string;
      email: string;
      role: string;
      status: string;
      expires_at: string;
    } | null;
  };

  if (!invitation) {
    return { error: "Invitación no encontrada o ya utilizada" };
  }

  if (new Date(invitation.expires_at) < new Date()) {
    return { error: "Esta invitación ha expirado" };
  }

  // Find the user in auth.users by email
  const {
    data: { users },
    error: userError,
  } = await supabaseAdmin.auth.admin.listUsers();

  if (userError) {
    console.error("[acceptInvitation] listUsers error:", userError);
    return { error: "Error al verificar tu cuenta. Intenta de nuevo." };
  }

  const authUser = users?.find(
    (u) => u.email?.toLowerCase() === invitation.email.toLowerCase(),
  );

  if (!authUser) {
    return {
      error:
        "No se encontró tu cuenta. Asegúrate de haber aceptado la invitación de Supabase y haber creado tu cuenta primero.",
    };
  }

  // Check if already a member
  const { data: existingMember } = await supabaseAdmin
    .from("clinic_users")
    .select("id")
    .eq("clinic_id", invitation.clinic_id)
    .eq("user_id", authUser.id)
    .maybeSingle();

  if (existingMember) {
    // Already a member, just mark invitation as accepted
    const query = supabaseAdmin.from("clinic_invitations") as any;
    await query
      .update({ status: "accepted", accepted_at: new Date().toISOString() })
      .eq("id", invitation.id);
    return { success: true };
  }

  // Create clinic_users row
  const { error: insertError } = await supabaseAdmin
    .from("clinic_users")
    .insert({
      clinic_id: invitation.clinic_id,
      user_id: authUser.id,
      role: invitation.role,
      display_name,
      email: invitation.email,
    } as any);

  if (insertError) {
    console.error("[acceptInvitation] insert error:", insertError);
    return { error: "Error al unirte a la clínica. Contacta con el administrador." };
  }

  // Mark invitation as accepted
  const query = supabaseAdmin.from("clinic_invitations") as any;
  await query
    .update({ status: "accepted", accepted_at: new Date().toISOString() })
    .eq("id", invitation.id);

  return { success: true };
}
